name: order-flow
channels:
  - conda-forge
dependencies:
  - python=3.14
  - chex=0.1.91
  - jax=0.7.2
  - Jinja2
  - jupyter
  - loguru=0.7.3
  - matplotlib=3.10.8
  - numpy=2.3.5
  - optax=0.2.6
  - pandas=2.3.3
  - plotly=6.5.0
  - polars=1.36.1
  - pyarrow=22.0.0
  - pytest=9.0.2
  - pytest-benchmark=5.2.3
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - seaborn>=0.13.2

# conda env update -f environment.yml --prune
